### ISSUE TITLE
Don't hardcode SLURM command paths

### ISSUE THREAD

**Issue by ColonelPanicks** [openflighthpc/queue-status-reporter#15]
On older systems or ones running stock slurm (not the OpenFlight build of it) the binary is stored elsewhere, perhaps add a "SLURM_BIN" variable if hardcoded paths are needed to be specified but just attempt to invoke via command name by default.

**Comment by VoxSecundus** [comment]
Can you think of any occasion where just running the command (without a path) would be unsuitable?

**Comment by ColonelPanicks** [comment]
The only situation I can think of is if this is run via cron on a system using OpenFlight's SLURM as the Flight User Suite acts non-intrusively so the command would not be in PATH.

I'd see myself setting this up to run daily/weekly via cron for various clusters running OpenFlight's SLURM build but I can fix this by invoking a script that sets PATH. Poor PATH setup seems to me like it would be on the user, not the tool 🤔

**Comment by VoxSecundus** [comment]
Cool, I'll take that as "just invoke the command and assume the user has set up PATH correctly".
