### ISSUE TITLE
Simple/Overview output

### ISSUE THREAD

**Issue by ColonelPanicks** [openflighthpc/queue-status-reporter#16]
In some cases, the overview information is enough to determine if we want to look further into the queue. There's a lot of information in outputs (especially for large cluster queues) such that it's difficult to determine if there's anything to worry about from a glance (and it can be quite a large message in terminal/slack to trawl through).

I suggest we add a flag to toggle between outputs, my initial feeling is that this simple/overview would be the default output and `--verbose` or something would provide the full queue breakdown.

Some thoughts of the key info: 

- Num idle nodes
- Num running jobs
- Num queued jobs
- Num jobs over runtime threshold
- Num jobs over queue wait threshold
- All jobs complete time

Example, open to interpretation.
```
## Queue Overview

### Nodes

X nodes of NUM_NODES are idle.

Nodes with no jobs in any of their partitions: NAME1 NAME2 NAME3

### Jobs

C jobs are running (D running for more than RUNTIME_THRESHOLD)
E jobs queued (F have been waiting for more than WAIT_THRESHOLD)
```

**Comment by timalces** [comment]
Resolved by #20
